---
- name: Install PHP dependencies
  composer:
    command: install
    working_dir: "{{ build_dir }}"
    no_dev: "{{ composer_no_dev }}"
    optimize_autoloader: "yes"

- name: Install JavaScript dependencies
  npm:
    path: "{{ build_dir }}"

- name: Compile JavaScript
  command: npm run build-js
  args:
    chdir: "{{ build_dir }}"

# @todo think about the differences between dev and prod (one-time vs repeated builds)
- name: Remove node modules
  file:
    path: "{{ build_dir }}/node_modules"
    state: absent
